#ifndef __WARANDOM_H__
#define __WARANDOM_H__

#include "watypes.h"
#include "waengine.h"

typedef void * WARAND_ENGINE_HANDLE;
typedef UL32 WATICKCOUNT;
typedef UL32 WARAND32;
typedef US16 WARAND16;
typedef UC8  WARAND8;

typedef UL32 WAENGINE_TYPES;

//Engine types
#define WARANROTB          0x00000001
#define WARANROTW          0x00000002
#define WAMERSENNE_TWISTER 0x00000004
#define WAMOTHER_OF_ALL    0x00000008
#define WAALL_RANDOM_TYPES (WAMOTHER_OF_ALL|WAMERSENNE_TWISTER|WARANROTW|WARANROTB)

WAEXPORT WARAND_ENGINE_HANDLE CreateWaRandManager(WORLD_ANALYSIS_ENGINE_HANDLE hWaEngine,
                           WATICKCOUNT (*TickCountFuncPtr)(),
                           WAENGINE_TYPES types);
WAEXPORT WARAND32 WaGenerateRand32(WARAND_ENGINE_HANDLE,WARAND32 min, WARAND32 max);
WAEXPORT WARAND16 WaGenerateRand16(WARAND_ENGINE_HANDLE,WARAND16 min, WARAND16 max);
WAEXPORT WARAND8  WaGenerateRand8(WARAND_ENGINE_HANDLE,WARAND8 min, WARAND8 max);
WAEXPORT NOTHING  DestroyWaRandManager(WARAND_ENGINE_HANDLE);

#endif